### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by leonardosnt** [SledgeMod/SledgeAPI#1]
You know that unturned was written in c#, right?

You already know how you'll implement?

**Comment by ThunderGemios10** [comment]
Yes, I am aware that Unturned was written in C#.
However, I am unsure how will i implement yet. I'm still learning how unturned works.

**Comment by khimboyz** [comment]
We are discussing on how we are implementing it.
But we need all the help we can get.
Like he said, if you are willing to help, free free to fork the repo ^_^
